# Generated by Django 5.1.6 on 2025-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_provider',
            field=models.CharField(blank=True, help_text="Authentication provider (e.g., 'google', 'facebook')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_provider',
            field=models.CharField(blank=True, help_text='Last provider used for login', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider_profile_url',
            field=models.URLField(blank=True, help_text="URL to user's profile at the provider", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provider_user_id',
            field=models.CharField(blank=True, help_text='User ID from the authentication provider', max_length=255, null=True),
        ),
    ]
