# Generated by Django 5.1.6 on 2025-03-06 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, max_length=50, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstagramInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_username", models.CharField(max_length=255)),
                (
                    "target_media_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("follow", "Follow"),
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("tag", "Tag"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instagram_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "instagram_account",
                            "target_username",
                            "interaction_type",
                        ],
                        name="instagram_i_instagr_86e01f_idx",
                    ),
                    models.Index(
                        fields=["target_media_id", "interaction_type"],
                        name="instagram_i_target__1ff9a5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "instagram_account",
                            "target_username",
                            "target_media_id",
                            "interaction_type",
                        ),
                        name="unique_instagram_interaction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InstagramMediaCache",
            fields=[
                (
                    "media_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("media_type", models.CharField(max_length=50)),
                ("permalink", models.URLField(max_length=500)),
                ("caption", models.TextField(blank=True, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instagram_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_cache",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["instagram_account", "timestamp"],
                        name="instagram_i_instagr_47e88a_idx",
                    )
                ],
            },
        ),
    ]
